apiVersion: v1
kind: Service
metadata:
  name: groundhogdai-client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: groundhogdai-client-pods
